codecov:
  ci:
    # by default, codecov doesn't recognize azure as a CI provider
    - dev.azure.com
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1
    patch: false
    changes: false

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
