version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # just so RTD stops complaining
    python: "latest"
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    pre_install:
      - git update-index --assume-unchanged docs/conf.py
    install:
      - pixi install -e docs
    build:
      html:
        - pixi run -e docs build-docs-rtd

sphinx:
  configuration: docs/conf.py
